name: My builds test

on: 
  pull_request:
    branches: main
  push:
    branches: main
#   push:
#     paths:
#       - '**.js'

jobs:
  build:

    name: my job
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        exclude:
          - os: macos-latest
            node-version: 12.x

    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! my name is
          FIRST_NAME: John
          MIDDLE_NAME: Chris
          LAST_NAME: Harry
          
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
        
      - name: my second job
        if: success()
        run: echo "The previous step has finished successfully!!"
        
      - name: my third step
        uses: actions/checkout@v2
        with:
          node-version: 12
          registry-url: https:///npm.pkg.github.com/
          
      - name: my fourth step
        uses: actions/first-interaction@master
        with:
          repo-token: {{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users first issue"
          pr-message: "message that will be displayed on run"
        
  
        
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
    
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [12.x, 14.x, 16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
